### ISSUE TITLE
`AieMlMemTileStrmSwSlavePortMap` is wrong

### ISSUE THREAD

**Issue by makslevental** [Xilinx/aie-rt#4]
https://github.com/Xilinx/aie-rt/blob/026da8272a7fd9b35a8bd07e2b0a6525526c112d/driver/src/global/xaiemlgbl_reginit.c#L1966-L1994

should be 

```c
	{
		/* PhyPort 11 */
		.PortType = SOUTH,
		.PortNum = 4,
	},
	{
		/* PhyPort 12 */
		.PortType = SOUTH,
		.PortNum = 5,
	},
	{
		/* PhyPort 13 */
		.PortType = NORTH,
		.PortNum = 0,
	},
	{
		/* PhyPort 14 */
		.PortType = NORTH,
		.PortNum = 1,
	},
	{
		/* PhyPort 15 */
		.PortType = NORTH,
		.PortNum = 2,
	},
	{
		/* PhyPort 16 */
		.PortType = NORTH,
		.PortNum = 3,
	},
```

See `Figure 6-9: Stream-switch ports and connectivity matrix` in arch spec.

cc @jtuyls

**Comment by newling** [comment]
This has been fixed upstream https://github.com/Xilinx/aie-rt/commit/69ae2d0c5a68b36d336e7a8d4c6e2c8efca5de18

**Comment by makslevental** [comment]
Thanks for letting me know.
